### ISSUE TITLE
Support more than 6 Nodes

### ISSUE THREAD

**Issue by ps915** [scottgchin/delta5_race_timer#11]
right now the trqacker is limited to 6 nodes. Is it possible to change the code to support 8 nodes?

would be awesome!

**Comment by MicroSystems** [comment]
My question is related to the ps915 question, why the program has a 6 nodes limitation and can it support 12 nodes ???

**Comment by scottgchin** [comment]
It was originally developed for 6 nodes because the club I fly with used IMD6.  It should be able to handle a lot more nodes, just that no one has tried yet.  It just requires some minor adjustments to the software to add more nodes.  We're looking into adding more nodes on future releases.

What VTX frequencies are you using to get 12 quads in the air without video issues?

**Comment by deepimpactio** [comment]
This can do it :P https://youtu.be/WlhNnn0CNxM https://youtu.be/R_jPfG8KLUs

**Comment by MicroSystems** [comment]
@scottgchin Actually we are 12 member and we fly in two groups 6 members at a time. i just wanted to make it a lot easier to all member to fly all at the same time, never tried it though.

**Comment by howflyquad** [comment]
Version 0.4 has been software limited to support 8 nodes.

Really all the needs to be figured out is what frequencies to assign as defaults beyond 8 nodes.
