### ISSUE TITLE
Map and constrain the RSSI value

### ISSUE THREAD

**Issue by scottgchin** [scottgchin/delta5_race_timer#2]
The RSSI value can be over 255 which isn't handled well by i2c unless the number is conditioned.  Possibly use the map() and constrain() functions to keep the values within range.

**Comment by shamshir1972** [comment]
scottgchin,
i've setup delta5 and got prob with python script. startstop.py seem to be not running at line 78 due to i2c device not present. Im using i2c device with address 14 (address of node 4 i2c) and channel 5860 (30). I got to delete other i2c device line and only remain the code for i2c address 14. Also at line 122 (while startstop==1) i got to remove other line not related to node 4 to get everything working. Please help me

**Comment by scottgchin** [comment]
If I understand you correctly, you're only using 1 node and it is using slave address 14 correct?

You need to delete the references to the other nodes because the pi is stuck waiting for a response from the arduinos (which are not there)  If that is the case you'll need to make the following changes to the startstop.py file:

Delete lines 70-72
Delete lines  74-83
Delete lines  86-104
Delete lines 111-119
Delete lines 124-194
Delete lines 220-266

**Comment by scottgchin** [comment]
The arduino file has been updated to ver 0.2 with adds the mapping and constrain functions to the RSSI read function.
